### DISCUSSION TITLE
Add textlint CI to enforce Japanese translation style guide

### DISCUSSION THREAD

**Discussion by jp-knj** [withastro/docs#11665] [Ideas]
## Summary
Maintain manual Japanese reviews is becoming increasingly time-consuming.  
We propose adding **textlint** to automatically enforce the existing
[Japanese Translation Guide](https://github.com/withastro/docs/blob/main/i18n-guides/%E6%97%A5%E6%9C%AC%E8%AA%9E.md).

## Motivation
- Review bandwidth is limited; >30% of JP PRs require style fixes.
- Our style guide already defines deterministic rules (敬体, no spaces between CJK & ASCII, terminology table, …).

## Proposed solution
1. Add `textlint` with the following initial rule set:
   - `textlint-rule-preset-jtf-style`
   - `textlint-rule-prh` with a custom dictionary generated from our terminology table
   - `textlint-rule-ja-no-space-between-half-and-full-width`
2. Run it in CI for `src/content/**/ja/**/*.md{,x}` only.
3. Fail the job on violations; provide `yarn lint:text --fix` for contributors.

```yaml
name: textlint
on:
  pull_request:
    paths:
      - "src/content/**/ja/**.md*"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: "latest" }
      - run: pnpm install --frozen-lockfile
      - run: pnpm textlint --format checkstyle "src/content/**/ja/**.md*"
```

## Prior art
- **nextjs-ja-translation/Nextjs-ja-translation-docs** enforces textlint at
  pre-commit and CI levels (linked below).
https://github.com/Nextjs-ja-translation/Nextjs-ja-translation-docs/blob/master/README.md?utm_source=chatgpt.com

## Open questions
- Should we gate merges on textlint errors immediately or start with warnings?
- Where to keep the prh dictionary (monorepo or sub-package)?

Feedback welcome!
