### ISSUE TITLE
Enable GitHub action for docs Congrats bot in Discord, like main repo

### ISSUE THREAD

**Issue by sarah11918** [withastro/docs#288]
Something based on this (from https://github.com/withastro/astro/blob/main/.github/workflows/main.yml)

```yml
jobs:
  congrats:
    name: congratsbot
    if: ${{ github.repository_owner == 'withastro' }}
    runs-on: ubuntu-latest
    steps:
      - id: setup
        env:
          MESSAGE: ${{ github.event.commits[0].message }}
        run:  |
              TRIMMED=$(echo "$MESSAGE" | sed '1!d;q')
              echo "::set-output name=COMMIT_MSG::${TRIMMED}"
      - name: Send a Discord notification when a PR is merged
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CONGRATS }}
          # DISCORD_AVATAR: ${{ github.event.pull_request.user.avatar_url }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: "**Merged!** ${{ github.event.commits[0].author.name }}: [`${{ steps.setup.outputs.COMMIT_MSG }}`](<https://github.com/withastro/astro/commits/main>)"
```
