### ISSUE TITLE
Broken images url for `Build a Blog` tutorial

### ISSUE THREAD

**Issue by dreamorosi** [withastro/docs#2975]
Following the tutorial "Build a Blog", at the step 2.2 - Write your first Markdown blog post, and section [Write Markdown Content](https://docs.astro.build/en/tutorial/2-pages/2/#write-markdown-content) the reader creates their first blog post.

The post contains an image in the front matter:
```yaml
image:
    url: 'https://astro.build/assets/blog/astro-1-release-update/cover.jpeg' 
    alt: 'The Astro logo with the word One.'
```

The url for the image returns a 404 and so the layout of the page at [step 4.2](https://docs.astro.build/en/tutorial/4-layouts/2/#try-it-yourself---customize-your-blog-post-layout) is incomplete.

The same happens for the other two images in the other two posts of the tutorial blog.

If one of the maintainers could indicate a replacement images to use I'd be happy to contribute a tiny PR with the fix.
